src/pages/myPage/MyPage.styled.ts, src/pages/myPage/MyPage.tsx
=> pr feat/#13-my-page-ui

src/components/bookmark/Bookmark.tsx, src/components/snowflake/PortfolioSnowflake.tsx, src/components/snowflake/Snowflake.tsx, src/components/snowflake/StockSnowflake.tsx, src/components/stock/grid/StockGrid.tsx, src/components/stock/grid/card/StockCard.tsx, src/components/stock/list/StockList.styled.ts, src/components/stock/list/StockList.tsx, src/components/stock/result/StockResult.tsx, src/pages/mainPage/MainPage.tsx, src/pages/mainPage/components/snowflake/Snowflake.tsx, src/pages/myPage/MyPage.tsx, src/pages/portfolioPage/PortfolioPage.styled.ts, src/pages/portfolioPage/PortfolioPage.tsx, src/pages/sharePortfolioPage/SharePortfolioPage.tsx, src/pages/sharePortfolioPage/portfolioCard/PortfolioCard.tsx, src/types/snowflakeTypes.ts, src/types/stockTypes.ts, src/utils/snowflakeUtils.ts
snowflake 그래프가 필요한 곳들의 데이터를 연결해보았습니다.
- 메인페이지 종목 리스트 
- 포트폴리오 종목 list
- 포트폴리오 종목 grid
- 공유 포트폴리오 목록
=> pr feat/#15-create-snowflake-graph

src/components/comment/list/CommentList.tsx, src/components/stock/list/StockList.tsx, src/main.tsx, src/pages/mainPage/components/snowflake/Snowflake.tsx, src/pages/portfolioPage/PortfolioPage.tsx, src/pages/sharePortfolioPage/portfolioCard/PortfolioCard.tsx, src/pages/stockPage/StockPage.tsx
=> pr fix/#22-build-error

package-lock.json, package.json, src/apis/index.ts, src/apis/portfolio.ts, src/apis/stock.ts, src/apis/user.ts, src/components/layouts/header/Header.tsx, src/components/layouts/header/autocomplete/Autocomplete.styled.ts, src/components/layouts/header/autocomplete/Autocomplete.tsx, src/types/stockTypes.ts
=> pr feat/#26-search-autocomplete

src/apis/stock.ts, src/components/comment/input/CommentInput.tsx
=> feat(#28): 댓글작성api 연결

src/apis/portfolio.ts, src/pages/mainPage/MainPage.tsx, src/pages/mainPage/components/recommendedFilter/RecommendedFilter.styled.ts, src/pages/mainPage/components/recommendedFilter/RecommendedFilter.tsx, src/pages/mainPage/components/snowflake/Snowflake.tsx, src/pages/mainPage/constants/defaultFilterItems.ts, src/types/portfolioTypes.ts, src/types/snowflakeTypes.ts, src/utils/snowflakeUtils.ts
- 인기 포트폴리오 조회 API 연결
- 전문가 포트폴리오 조회 API 연결
- 나의 포트폴리오 저장 API 연결
: 현재 response로 포트폴리오 id가 오지않아서, response가 추가된다면 해당 포트폴리오로 페이지 이동 기능을 추가할 예정입니다.
=> pr feat/#31-main-page-portfolio-api

src/apis/stock.ts, src/pages/mainPage/MainPage.styled.ts, src/pages/mainPage/MainPage.tsx, src/pages/mainPage/components/snowflake/Snowflake.tsx, src/pages/mainPage/hooks/useThresholds.ts
임계값 조회 API를 연결하였습니다. 또한 임계값에 해당하는 투자지표 값을 반환 후, UI로 구현하였습니다. 
현재 임계값 데이터가 20개씩 오는데, 
21개씩 오는 것으로 api 변경 후, 다시 확인이 필요합니다.
=> pr feat/#50-thresholds-api

src/pages/mainPage/MainPage.tsx
snowflake 필터 임계값 조회시, 20개의 데이터만 오기 때문에 (21개 필요)
snowflake 필터의 0점 값에 마이너스 무한대를 넣어 UI로 표현하였습니다.
=> pr feat/#58-snowflake-filter-add-min-threshold

src/components/stock/result/StockResult.styled.ts, src/components/stock/result/StockResult.tsx, src/pages/mainPage/MainPage.styled.ts, src/pages/mainPage/MainPage.tsx, src/pages/mainPage/components/snowflake/Snowflake.tsx
snowflake filter에서 그래프 조정이 아닌 직접 값을 입력할 수 있는 기능을 추가했습니다.
MainPage.tsx 파일은 코드 리팩토링 예정입니다.
=> pr feat/#62-snowflake-filter-input

src/pages/mainPage/MainPage.tsx
메인 페이지에서 유저 권한이 없을 시, API 무한 요청을 보내는 오류를 해결하였습니다.
=> pr fix/#77-main-page-api-infinite-request

src/apis/portfolio.ts, src/pages/portfolioPage/myPortfolioPage/MyPortfolioPage.tsx, src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx
- 나의 포트폴리오 공유 API 연결 
- 나의 포트폴리오 삭제 API 연결
- 남의 포트폴리오 가져오기 (저장) API 연결
=> pr Feat/#94 my share portfolio graph data api

src/apis/portfolio.ts, src/components/comment/input/CommentInput.tsx, src/components/comment/list/CommentList.tsx
- 댓글 input 위에 닉네임이 나타나도록 코드를 수정했습니다. 
- 수정 버튼을 클릭했을 때, 드롭박스가 계속 떠 있는 문제를 해결했습니다.
=> pr Fix/#107 fix stock page

src/apis/portfolio.ts, src/components/comment/input/CommentInput.tsx, src/components/comment/list/CommentList.tsx, src/components/layouts/header/Header.tsx, src/pages/portfolioPage/myPortfolioPage/MyPortfolioPage.tsx, src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx
포트폴리오 관련하여 오류 해결 및 추가 기능을 구현하였습니다.
- 공유 포트폴리오 - 댓글 총 개수 띄우기
- 나의 포트폴리오 - 새로운 포트폴리오 만들기 링크 이동
- 나의 포트폴리오 - 종목 리스트 아이템 클릭 시, 해당 페이지로 이동
- 나의 포트폴리오 - 삭제 시, 페이지 이동 처리
- 나의 포트폴리오 - 로그인 필요 alert 추가
- 공유 포트폴리오 댓글 - placeholder 수정
- 비로그인 시, 댓글 작성 제어
=> pr fix/#106-portfolio-feature

src/index.css
=> pr fix/#116-font-setting

src/components/layouts/header/Header.tsx, src/components/stock/grid/card/StockCard.tsx, src/components/stock/list/StockList.tsx, src/pages/mainPage/MainPage.tsx, src/pages/stockPage/StockPage.tsx, src/utils/transferUtils.ts
로그아웃 및 주식 종목 리스트 조회에서 현재가가 없는 경우 예외 처리
=> pr fix/#127-로그아웃 수정

src/components/snowflake/StockSnowflake.tsx
- 주식 스노우 플래이크 필터 크기에 따른 색상 변경을 적용했습니다.
=> pr Fix/#121 fix specific filtering condition

src/pages/stockPage/StockPage.tsx
- 경쟁사 페이지 클릭 시 해당 종목으로 이동하는 코드를 구현했습니다.
=> pr feat(#138): 경쟁사 페이지 클릭 시 해당 종목으로 이동 구현

src/pages/mainPage/MainPage.tsx, src/pages/mainPage/components/snowflake/Snowflake.tsx, src/pages/stockPage/StockPage.tsx, src/types/snowflakeTypes.ts, src/types/stockTypes.ts
조건 검색 결과 조회의 에러를 해결합니다
- 조건 검색 결과 조회 에러 해결
- Snowflake 0 제어
추가적으로
- 종목 페이지 - snowflake 그래프 투자지표 순서
- 종목 페이지 - 경쟁사 snowflake divYield 한글 매핑
를 구현하였습니다.
=> pr fix/#134-snowflake-filter-error

src/components/layouts/header/Header.tsx, src/components/lineGraph/LineGraphStock.tsx, src/pages/mainPage/components/filterGroup/FilterGroup.tsx
=> deploy(#142): 빌드를 위한 오류 해결

src/pages/mainPage/MainPage.tsx, src/types/snowflakeTypes.ts
메인 페이지 - 배당 수익률 안보이는 문제 해결 
메인 페이지 - 추천 필터 선택 시, 마켓이 ALL로 표시
를 수정하였습니다.
=> pr fix/#150-main-page-dividend-yield

src/components/comment/Comment.tsx, src/components/comment/list/CommentList.tsx, src/pages/portfolioPage/sharePortfolioPage/SharePortfolioDetailPage.tsx, src/pages/stockPage/StockPage.tsx
- 종목, 공유 포트폴리오 댓글 생성, 수정 시 렌더링 되는 문제를 해결했습니다.
- 수정 버튼 모달이 닫히지 않는 문제를 해결했습니다.
=> pr Fix/#145 fix stock comment create update rendering

src/components/comment/list/CommentList.tsx
=> pr deploy/#160-fix-build-error
